services:
  - type: web
    name: cloud-web
    region: frankfurt
    plan: free
    runtime: node
    repo: https://github.com/ArchOrn/render-deploy-bp.git
    branch: master
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  - name: cloud-db
    region: frankfurt
    plan: free
    databaseName: cloud
    user: cloud
