services:
  # A Docker web service
  - type: web
    name: cloud_blueprint
    runtime: node
    repo: https://github.com/Stooms21/ESGI_render_blueprint # optional
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    buildCommand: npm install
    startCommand: npm run start
    envVars:
    	key: DATABASE_URL
    	fromDatabase:
            name: cloud-db
            property: connectionString

database:
    name: cloud-db
    region: frankfurt
    
	
